// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Ethers$FlowsUserApp from "../../lib/Ethers/Ethers.bs.js";
import * as AuthProvider$FlowsUserApp from "../../lib/Auth/AuthProvider.bs.js";
import * as RootProvider$FlowsUserApp from "../../lib/Old/RootProvider.bs.js";

function setSignInData(ethAddress, ethSignature) {
  localStorage.setItem(ethAddress, ethSignature);
  
}

function AuthenticateButton(Props) {
  var signer = RootProvider$FlowsUserApp.useSignerExn(undefined);
  var userAddress = RootProvider$FlowsUserApp.useCurrentUserExn(undefined);
  var match = AuthProvider$FlowsUserApp.useAuthStatus(undefined);
  var setIsAuthorized = match.setIsAuthorized;
  return React.createElement("button", {
              onClick: (function (param) {
                  signer.signMessage("flows.finance-signin-string:" + Ethers$FlowsUserApp.Utils.ethAdrToStr(userAddress)).then(function (result) {
                        setSignInData(Ethers$FlowsUserApp.Utils.ethAdrToLowerStr(userAddress), String(result));
                        return Curry._1(setIsAuthorized, (function (param) {
                                      return true;
                                    }));
                      });
                  
                })
            }, "Authenticate");
}

var make = AuthenticateButton;

export {
  setSignInData ,
  make ,
  
}
/* react Not a pure module */
