// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RaidenTs from "raiden-ts";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as RootProvider$FlowsUserApp from "./lib/Old/RootProvider.bs.js";

function Dapp(Props) {
  var optWeb3Provider = RootProvider$FlowsUserApp.useWeb3(undefined);
  var optSigner = RootProvider$FlowsUserApp.useSigner(undefined);
  React.useEffect((function () {
          if (optWeb3Provider !== undefined && optSigner !== undefined) {
            RaidenTs.create(Caml_option.valFromOption(optWeb3Provider), 0);
          }
          
        }), [
        optWeb3Provider,
        optSigner
      ]);
  return React.createElement("div", undefined, React.createElement("p", undefined, "something"));
}

var make = Dapp;

export {
  make ,
  
}
/* react Not a pure module */
