// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as App$FlowsUserApp from "./App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$FlowsUserApp.make, {}), "root");

export {
  
}
/*  Not a pure module */
