// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.bs.js";

function fromUrl(url) {
  var match = url.path;
  if (match) {
    if (match.hd === "login" && !match.tl) {
      return /* Login */1;
    } else {
      return ;
    }
  } else {
    return /* Main */0;
  }
}

function useRouter(param) {
  return fromUrl(ReasonReactRouter.useUrl(undefined, undefined));
}

export {
  fromUrl ,
  useRouter ,
  
}
/* ReasonReactRouter Not a pure module */
