// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Test(Props) {
  var renderString = Props.renderString;
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  React.useEffect((function () {
          Curry._1(setCount, (function (param) {
                  return count + 1 | 0;
                }));
          
        }), [renderString]);
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, renderString), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (param) {
                                    return count + 1 | 0;
                                  }));
                    })
                }, String(count)));
}

var make = Test;

export {
  make ,
  
}
/* react Not a pure module */
