// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Ethers$FlowsUserApp from "./lib/Ethers/Ethers.bs.js";
import * as Queries$FlowsUserApp from "./Queries.bs.js";
import * as RootProvider$FlowsUserApp from "./lib/Old/RootProvider.bs.js";

function ViewStreams(Props) {
  var user = RootProvider$FlowsUserApp.useCurrentUserExn(undefined);
  var viewStreamsQuery = Curry.app(Queries$FlowsUserApp.ViewPaymentsStreamsWithAddress.use, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        {
          address: Ethers$FlowsUserApp.Utils.ethAdrToStr(user)
        }
      ]);
  var match = viewStreamsQuery.data;
  var tmp;
  var exit = 0;
  if (match !== undefined || !viewStreamsQuery.loading) {
    exit = 1;
  } else {
    tmp = React.createElement("p", undefined, "Loading");
  }
  if (exit === 1) {
    var error = viewStreamsQuery.error;
    if (error !== undefined) {
      console.log(error);
      tmp = React.createElement("p", undefined, "Data is loaded");
    } else {
      tmp = match !== undefined ? Belt_Array.map(match.streams, (function (param) {
                var id = param.id;
                return React.createElement("div", {
                            key: String(id)
                          }, String(id), React.createElement("br", undefined), String(param.amount), React.createElement("br", undefined), String(param.interval), React.createElement("br", undefined), String(param.numberOfPayments), React.createElement("br", undefined), String(param.numberOfPaymentsMade), React.createElement("br", undefined), String(param.recipient), React.createElement("br", undefined), String(param.state), React.createElement("br", undefined), String(param.tokenAddress), React.createElement("br", undefined), String(param.startPayment), React.createElement("br", undefined), String(param.nextPayment), React.createElement("br", undefined), String(param.lastPayment));
              })) : React.createElement("p", undefined, "Error loading data");
    }
  }
  return React.createElement("div", undefined, tmp);
}

var make = ViewStreams;

export {
  make ,
  
}
/* react Not a pure module */
