// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var BnJs = require("bn.js");

var big1 = new BnJs(1);

var big60 = new BnJs(60);

exports.big1 = big1;
exports.big60 = big60;
/* big1 Not a pure module */
