// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Ethers = require("ethers");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

function unsafeToOption(unsafeFunc) {
  try {
    return Caml_option.some(Curry._1(unsafeFunc, undefined));
  }
  catch (raw__obj){
    var _obj = Caml_js_exceptions.internalToOCamlException(raw__obj);
    if (_obj.RE_EXN_ID === Js_exn.$$Error) {
      return ;
    }
    throw _obj;
  }
}

var Misc = {
  unsafeToOption: unsafeToOption
};

function makeAbi(abiArray) {
  return abiArray;
}

var BigNumber = {};

var Wallet = {};

var Providers = {};

function make(address, abi, providerSigner) {
  return new Ethers.Contract(address, abi, providerSigner._0);
}

var Contract = {
  make: make
};

function parseUnits(amount, unit) {
  return unsafeToOption(function (param) {
              return Ethers.utils.parseUnits(amount, unit);
            });
}

function parseEther(amount) {
  return parseUnits(amount, "ether");
}

function getAddress(addressString) {
  return unsafeToOption(function (param) {
              return Ethers.utils.getAddress(addressString);
            });
}

function toString(prim) {
  return prim;
}

function toLowerString(address) {
  return address.toLowerCase();
}

var Utils = {
  parseUnits: parseUnits,
  parseEther: parseEther,
  getAddress: getAddress,
  toString: toString,
  toLowerString: toLowerString
};

exports.Misc = Misc;
exports.makeAbi = makeAbi;
exports.BigNumber = BigNumber;
exports.Wallet = Wallet;
exports.Providers = Providers;
exports.Contract = Contract;
exports.Utils = Utils;
/* ethers Not a pure module */
