// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function AutoRenewToggleStreamModal(Props) {
  return React.createElement("div", undefined, "Modal to toggle setting autorenew on and off", "Cancel & Confirm");
}

var make = AutoRenewToggleStreamModal;

export {
  make ,
  
}
/* react Not a pure module */
