// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function DeleteStreamModal(Props) {
  return React.createElement("div", undefined, "Modal to approve confirm deleting stream", "Cancel & Confirm");
}

var make = DeleteStreamModal;

export {
  make ,
  
}
/* react Not a pure module */
