// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import EthereumBlockiesBase64 from "ethereum-blockies-base64";

function ContactsTable(Props) {
  return React.createElement("div", {
              className: "flex flex-col"
            }, React.createElement("div", {
                  className: "my-2 overflow-x-auto sm:-mx-6 lg:-mx-8"
                }, React.createElement("div", {
                      className: "py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8"
                    }, React.createElement("div", {
                          className: "shadow overflow-hidden border-b border-gray-200"
                        }, React.createElement("table", {
                              className: "min-w-full divide-y divide-gray-200"
                            }, React.createElement("thead", {
                                  className: "bg-gray-50"
                                }, React.createElement("tr", undefined, React.createElement("th", {
                                          className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider",
                                          scope: "col"
                                        }, "Name"), React.createElement("th", {
                                          className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider",
                                          scope: "col"
                                        }, "Description"), React.createElement("th", {
                                          className: "relative px-6 py-3",
                                          scope: "col"
                                        }, React.createElement("span", {
                                              className: "sr-only"
                                            }, "Edit")))), React.createElement("tbody", {
                                  className: "bg-white divide-y divide-gray-200"
                                }, React.createElement("tr", undefined, React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap"
                                        }, React.createElement("div", {
                                              className: "flex items-center"
                                            }, React.createElement("div", {
                                                  className: "flex-shrink-0 h-10 w-10"
                                                }, React.createElement("img", {
                                                      src: EthereumBlockiesBase64("0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8")
                                                    })), React.createElement("div", {
                                                  className: "ml-4"
                                                }, React.createElement("div", {
                                                      className: "text-sm font-medium text-gray-900"
                                                    }, "World Hello"), React.createElement("div", {
                                                      className: "text-sm text-gray-500"
                                                    }, "0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8")))), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500"
                                        }, "Software Engineer"), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                                        }, React.createElement("a", {
                                              className: "text-indigo-600 hover:text-indigo-900",
                                              href: "#"
                                            }, "Edit"))), React.createElement("tr", undefined, React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap"
                                        }, React.createElement("div", {
                                              className: "flex items-center"
                                            }, React.createElement("div", {
                                                  className: "flex-shrink-0 h-10 w-10"
                                                }, React.createElement("img", {
                                                      src: EthereumBlockiesBase64("0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B")
                                                    })), React.createElement("div", {
                                                  className: "ml-4"
                                                }, React.createElement("div", {
                                                      className: "text-sm font-medium text-gray-900"
                                                    }, "Arthur Kambrook"), React.createElement("div", {
                                                      className: "text-sm text-gray-500"
                                                    }, "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B")))), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500"
                                        }, "Maker of fans"), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                                        }, React.createElement("a", {
                                              className: "text-indigo-600 hover:text-indigo-900",
                                              href: "#"
                                            }, "Edit"))), React.createElement("tr", undefined, React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap"
                                        }, React.createElement("div", {
                                              className: "flex items-center"
                                            }, React.createElement("div", {
                                                  className: "flex-shrink-0 h-10 w-10"
                                                }, React.createElement("img", {
                                                      src: EthereumBlockiesBase64("0x024245FEdaAb1052e4491A8e0b348D8AaF16eEE7")
                                                    })), React.createElement("div", {
                                                  className: "ml-4"
                                                }, React.createElement("div", {
                                                      className: "text-sm font-medium text-gray-900"
                                                    }, "Vitalik Buterin"), React.createElement("div", {
                                                      className: "text-sm text-gray-500"
                                                    }, "0x024245FEdaAb1052e4491A8e0b348D8AaF16eEE7")))), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500"
                                        }, "Father of Ethereum"), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                                        }, React.createElement("a", {
                                              className: "text-indigo-600 hover:text-indigo-900",
                                              href: "#"
                                            }, "Edit"))), React.createElement("tr", undefined, React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap"
                                        }, React.createElement("div", {
                                              className: "flex items-center"
                                            }, React.createElement("div", {
                                                  className: "flex-shrink-0 h-10 w-10"
                                                }, React.createElement("img", {
                                                      src: EthereumBlockiesBase64("0xDa0264D7B90FF0e7EDa6e0548a542012Ccd7F34f")
                                                    })), React.createElement("div", {
                                                  className: "ml-4"
                                                }, React.createElement("div", {
                                                      className: "text-sm font-medium text-gray-900"
                                                    }, "Paul Simon"), React.createElement("div", {
                                                      className: "text-sm text-gray-500"
                                                    }, "0xDa0264D7B90FF0e7EDa6e0548a542012Ccd7F34f")))), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500"
                                        }, "Great musician"), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                                        }, React.createElement("a", {
                                              className: "text-indigo-600 hover:text-indigo-900",
                                              href: "#"
                                            }, "Edit"))), React.createElement("tr", undefined, React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap"
                                        }, React.createElement("div", {
                                              className: "flex items-center"
                                            }, React.createElement("div", {
                                                  className: "flex-shrink-0 h-10 w-10"
                                                }, React.createElement("img", {
                                                      src: EthereumBlockiesBase64("0xf42C679437d08dd0d695f90b23Ca22F2e858FC2b")
                                                    })), React.createElement("div", {
                                                  className: "ml-4"
                                                }, React.createElement("div", {
                                                      className: "text-sm font-medium text-gray-900"
                                                    }, "Leonardo di Caprio"), React.createElement("div", {
                                                      className: "text-sm text-gray-500"
                                                    }, "0xf42C679437d08dd0d695f90b23Ca22F2e858FC2b")))), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-sm text-gray-500"
                                        }, "Rose's husband"), React.createElement("td", {
                                          className: "px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                                        }, React.createElement("a", {
                                              className: "text-indigo-600 hover:text-indigo-900",
                                              href: "#"
                                            }, "Edit")))))))));
}

var make = ContactsTable;

export {
  make ,
  
}
/* react Not a pure module */
