// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.bs.js";
import * as Ethers$FlowsUserApp from "../lib/Ethers/Ethers.bs.js";
import * as RootProvider$FlowsUserApp from "../lib/Old/RootProvider.bs.js";
import * as DisplayAddress$FlowsUserApp from "./DisplayAddress.bs.js";

function Nav(Props) {
  var user = RootProvider$FlowsUserApp.useCurrentUser(undefined);
  var network = RootProvider$FlowsUserApp.useNetworkName(undefined);
  var logout = RootProvider$FlowsUserApp.useDeactivateWeb3(undefined);
  return React.createElement("div", {
              className: "container mx-auto py-4"
            }, React.createElement("div", {
                  className: "flex justify-between items-center"
                }, React.createElement("a", {
                      className: "flex items-center",
                      href: "https://flows.finance"
                    }, React.createElement("img", {
                          className: "h-10",
                          src: "/img/flows_finance_logo.svg"
                        }), React.createElement("h2", {
                          className: "pl-4 text-xl"
                        }, "Flows Finance")), user !== undefined ? React.createElement("ul", {
                        className: "flex items-center"
                      }, React.createElement("li", {
                            className: "pl-4 uppercase flex  items-center",
                            onClick: (function (_e) {
                                return ReasonReactRouter.push("/");
                              })
                          }, React.createElement("img", {
                                className: "h-3 pr-1",
                                src: "/img/icons/dashboard.svg"
                              }), "Dashboard"), React.createElement("li", {
                            className: "pl-4 uppercase flex items-center",
                            onClick: (function (_e) {
                                return ReasonReactRouter.push("stream");
                              })
                          }, React.createElement("img", {
                                className: "h-3 pr-1",
                                src: "/img/icons/stream.svg"
                              }), "Create Stream"), React.createElement("li", {
                            className: "pl-4 flex  items-center"
                          }, React.createElement(DisplayAddress$FlowsUserApp.make, {
                                address: Ethers$FlowsUserApp.Utils.ethAdrToStr(Caml_option.valFromOption(user))
                              }), React.createElement("img", {
                                className: "h-3 pl-1",
                                src: "/img/icons/logout.svg",
                                onClick: (function (_e) {
                                    return Curry._1(logout, undefined);
                                  })
                              })), React.createElement("li", {
                            className: "pl-4"
                          }, React.createElement("div", {
                                className: "rounded-md py-1 px-3 bg-indigo-600 bg-opacity-25 uppercase"
                              }, network))) : React.createElement("button", {
                        className: "uppercase px-2"
                      }, "connect")));
}

var make = Nav;

export {
  make ,
  
}
/* react Not a pure module */
