// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var GqlConverters = require("./GqlConverters.bs.js");

function bnDecoder(bnJsonString) {
  return {
          TAG: /* Ok */0,
          _0: GqlConverters.$$BigInt.parse(bnJsonString)
        };
}

var bnCoder_0 = GqlConverters.$$BigInt.serialize;

var bnCoder = [
  bnCoder_0,
  bnDecoder
];

exports.bnDecoder = bnDecoder;
exports.bnCoder = bnCoder;
/* GqlConverters Not a pure module */
