// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var BnJs = require("bn.js");
var Js_json = require("bs-platform/lib/js/js_json.js");

function parse(prim) {
  return new BnJs(prim);
}

function serialize(prim) {
  return prim.toString();
}

var $$BigInt = {
  parse: parse,
  serialize: serialize
};

function parse$1(prim) {
  return new BnJs(prim);
}

function serialize$1(prim) {
  return prim.toNumber();
}

var IntToBigInt = {
  parse: parse$1,
  serialize: serialize$1
};

function parse$2(json) {
  var str = Js_json.decodeString(json);
  if (str !== undefined) {
    return str;
  } else {
    console.log("CRITICAL - should never happen!");
    return "couldn't decode bytes";
  }
}

function serialize$2(bytesString) {
  return bytesString;
}

var Bytes = {
  parse: parse$2,
  serialize: serialize$2
};

exports.$$BigInt = $$BigInt;
exports.IntToBigInt = IntToBigInt;
exports.Bytes = Bytes;
/* bn.js Not a pure module */
