// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function errorToMessageAndStacktrace(error) {
  return [
          String(error),
          error.stack
        ];
}

exports.errorToMessageAndStacktrace = errorToMessageAndStacktrace;
/* No side effect */
