// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var HdWalletProvider = {};

var PrivateKeyProvider = {};

var Web3 = {};

var EthereumAbi = {};

function getEthSig(sigString) {
  return {
          signature: sigString,
          r: sigString.slice(0, 66),
          s: "0x" + sigString.slice(66, 130),
          v: parseInt(sigString.slice(130, 132), 16)
        };
}

var ethPrefix = "\x19Ethereum Signed Message:\n32";

exports.HdWalletProvider = HdWalletProvider;
exports.PrivateKeyProvider = PrivateKeyProvider;
exports.Web3 = Web3;
exports.EthereumAbi = EthereumAbi;
exports.getEthSig = getEthSig;
exports.ethPrefix = ethPrefix;
/* No side effect */
